### ISSUE TITLE
Notifications not working without Google Play Services

### ISSUE THREAD

**Issue by TheoDutch** [CorvetteCole/GotoSleep#10]
Notifications seem to be dependent on Google Play Services. I am running lineageOS without Google Play Services. Would it be an idea to look into Pushy (https://pushy.me)?

**Comment by CorvetteCole** [comment]
what version of Android are you running? I'm using basic Alarms so it really shouldn't be dependent on GMS. Am looking in to this

**Comment by TheoDutch** [comment]
Thank you for your quick response. You were right, the issue is nog Google Play Services. The problem was that my phone automatically goes to 'Do-not-disturb' mode when its late. This is of course not an issue with your app. I really like the idea of the app :)
