### ISSUE TITLE
Bug found in Go to Sleep - sleep reminder app ( cannot open the application)

### ISSUE THREAD

**Issue by nasirshah1813** [CorvetteCole/GotoSleep#17]
#### Project Information

* Repository: https://github.com/CorvetteCole/GotoSleep

* Project Name: Go to Sleep - sleep reminder app

* Publisher : Cole.Dev

#### Expected behavior

according to my information when I try to open the Go to Sleep - sleep reminder app. the application should be opened and we can access all the features of the app
  

#### Actual behavior

after download and install the application when I try to open the application   the application cannot open and forcedly close automatically   you can see in bug video properly

#### How to reproduce
* Download  the application 
* install the application 
* click on the icon for open the application
* Note the bug 

* App version:   1.2.5.7

* Operating system: Android version 7.0

* Smart Phone: HUAWEI MATE 10 LITE

#### Recording Of The Bug

https://youtu.be/acqIAlPF-lM

#### GitHub Account

https://github.com/nasirshah1813

**Comment by CorvetteCole** [comment]
Hi, I will look in to this bug later today. Looks like it is probably
caused by your phone vs the app but I may be able to fix it from my side

**Comment by nasirshah1813** [comment]
Sir my phone is okay many other  apps running corectly  may be this is bug of your application
