### ISSUE TITLE
Alternative Download source?

### ISSUE THREAD

**Issue by IzzySoft** [CorvetteCole/GotoSleep#3]
Currently, your app is only available at Google Play – so folks without that cannot install it. Would you mind making it available to the "Google Free" section – e.g. by attaching the APK to your `releases/`, or even bringing your app to [F-Droid](https://f-droid.org/)?

**Comment by CorvetteCole** [comment]
currently I'm trying to ride a fine line between discouraging purchases by offering the APK easily and also supporting the open source nature of the app. I am investigating bringing the app to F-droid currently. You bring up a good point though, I'd be willing to assume a minority of people would download the app from GitHub vs downloading it from the play store. I will look in to de-googlefying the next version and releasing that on here.

**Comment by IzzySoft** [comment]
Thanks a lot! And yes, exactly that seems to be the case. There are some other apps with similar "problems" (being paid on Play and free on F-Droid): OsmAnd, DAVx5 (formerly DAVDroid), Conversations coming to mind. Seems most people rather pay on Play then go through the troubles of "unknown sources".

For me, it's a free decision to avoid Play (mainly for privacy and security – most apps on Play come with far too many trackers (ahem, more than zero that is)). While when installing from Play I'd need to check before each update what might have been added, with F-Droid I have no such issues.

Which is also a reason I promote and recommend F-Droid – and recently went so far that I'm now one of the maintainers there :innocent: So feel free to ping me if you need help getting your app listed at F-Droid :smiley: 

PS: You might consider some donation link. That should then be present here at your app's repo as well for verification when we add the app on F-Droid.

**Comment by IzzySoft** [comment]
:hand: <- offer :wink: 

As I wrote, we'll assist you. In short, I could setup the RFP including all necessary Metadata, then the bot checks your repo if all is "acceptable" – and then we see. In the best case, you'll simply note your app is listed (happens if no issues arise) – otherwise we might ask you for help (making some adjustments). Should it be to overtaxing you, we always can put it "on hold" to either picked up later or (hopefully not) be "delayed forever" (RFP closed).

Once it's listed, all you've got to do is keep up tagging for new versions to be discovered automatically – so nothing you wouldn't do anyway.

How does that sound? Shall I trigger the process?

**Comment by CorvetteCole** [comment]
Absolutely, I'm game. You may want to wait a bit so I can make a branch without any of the google billing libraries etc and removed the code regarding that stuff. Then I'll just merge updates from the main branch with minor modifications. I've created the new branch and will be working on removing google stuff etc from it shortly. https://github.com/CorvetteCole/GotoSleep/tree/de-googled_f-droid

**Comment by CorvetteCole** [comment]
Hi there, sorry to spam your notifications! I've completed a de-googled version at that branch (https://github.com/CorvetteCole/GotoSleep/tree/de-googled_f-droid) which should just compile and work without any google things at all (it did in my testing). It will be fairly straightforward for me to maintain both branches

**Comment by CorvetteCole** [comment]
Hey thanks so much for your help. I'll definitely look in to adding screenshots to F-droid through that in a bit

**Comment by aharish** [comment]
@CorvetteCole Will the de-googleified branch also mean that others who wish to contribute can now do so without adding extra work for both of us?

**Comment by CorvetteCole** [comment]
@aharish yep! I added that to the readme compile instructions. You can just clone and build that branch and you're good to go!

**Comment by CorvetteCole** [comment]
@IzzySoft one more question, do I have to do anything special when I update the app's branch to a new version?

**Comment by IzzySoft** [comment]
Increase versionName/versionCode, and tag the release. While it's in my repo, also attach an APK (not needed for the official repo, once the app is there). Apart from that, usually nothing. I've set the Metadata for auto-update on new tags, so it should check them and pull updates automatically, once detected.

**Comment by IzzySoft** [comment]
That would mean opening a merge request for the metadata file (or open an issue asking that someone does it, or ping me to do it :wink:) Things you can maintain in your own repo (via Fastlane/Triple-T) are screenshots, description and summary. For the latter two, a single MR is needed once you've set that up (and created a new tag afterwards) to remove them from the metadata file, as otherwise that would override your data.

**Comment by CorvetteCole** [comment]
awesome. I'll try and set up the fastlane/Triple-t stuff in a bit to do that then I'll submit a MR to F-droid changing the website URL and removing the stuff that would override things I set up. Thanks again!

**Comment by IzzySoft** [comment]
You're welcome! Seeing you then in that MR. Or, as the initial one hasn't yet been processed, we might be able to fix that up right away. For example, the website I could replace now if you want (just say what I shall put). If you're ready with Fastlane/Triple-T before the initial merge, we can integrate that as well (provided it's already tagged). So just 1) let me know what I should adjust now and 2) ping me when the other parts are ready.

**Comment by CorvetteCole** [comment]
@IzzySoft I'd love if you could adjust the website in the F-droid merge request to be "https://sleep.corvettecole.com/". I'm reading the documentation on Fastlane/Triple-T now

**Comment by IzzySoft** [comment]
Done. Waiting for your next "ping" then. Good luck!

**Comment by IzzySoft** [comment]
After the bot was fixed (glad I managed to) and [scanned your repo](https://gitlab.com/fdroid/rfp/issues/868#note_132732538) (ignore the "scanner-error": looks like it didn't follow the tag but scanned "master"): one minor thing you might wish to check is the "scanner-warning" on your gradlew. Not important for us (we work around that), but for your own releases.

I signaled our "integrators" to take a look. Hopefully your app will be integrated soon! How are you getting along with Fastlane/Triple-T?

**Comment by IzzySoft** [comment]
OK, get ready: Metadata have just been merged. With the next build run, your app should be built – and a few days later show up in the index. Can't be more than 2 weeks now :raised_hands:

**Comment by IzzySoft** [comment]
Uh, while that is going forward, the APK attached to your latest release is not signed:

    ERROR: No signing certificates found in repo/com.corvettecole.gotosleep_1.2.5.5.apk
    WARNING: Skipping 'com.corvettecole.gotosleep_1.2.5.5.apk' with invalid signature!

That means, the update didn't reach my repo. Could you please fix that one more time?

**Comment by CorvetteCole** [comment]
Yeah absolutely, I swear I signed it, super weird.

**Comment by IzzySoft** [comment]
I don't doubt you. Had at least one case before that was similar (author sweared he signed it and still it wasn't). Strange things…

**Comment by CorvetteCole** [comment]
> I don't doubt you. Had at least one case before that was similar (author sweared he signed it and still it wasn't). Strange things…

Hey the app is now available in F-droid. Still want me to re-upload a new APK? Thanks for your help btw

**Comment by IzzySoft** [comment]
Yes, that was a success :smiley:

As for the APK: I removed your app from my repo when it was listed in the official one (otherwise it would lead to confusion due to the signature not matching), so I wouldn't need the APK currently. Others might welcome it (and in the case updates get stuck in F-Droid for one reason or another, it cannot hurt either). Up to you :wink:
